# Task 1.1: Application of Python-based geospatial visualisation tool (e.g., GeoPandas) on a real- world dataset

In [2]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

In [7]:
import os
os.chdir("jamalamro25-Geospatial-Analysis-Refugee-data")

In [8]:
refugee = pd.read_csv("data/persons_of_concern_demographics.csv")

In [9]:
refugee.head()

,Year,Country of Asylum,Country of Origin,Country of Asylum ISO,Country of Origin ISO,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
0,2001,-,Afghanistan,-,AFG,192279,304463,260994,582552,40557,6717,1387562,195602,323327,277122,785010,57395,8854,1647310,5140545
1,2001,-,Iran (Islamic Rep. of),-,IRN,1721,2794,2440,6352,458,1330,15095,1767,2961,2560,7830,560,2122,17800,106628
2,2001,-,Iraq,-,IRQ,2488,20261,17390,127005,11755,1789,180688,2501,21658,18542,185983,10963,2710,242357,578334
3,2001,-,North Macedonia,-,MKD,1019,2088,1805,8080,1383,74,14449,1159,2234,1933,7255,1190,86,13857,30788
4,2001,-,Serbia and Kosovo: S/RES/1244 (1999),-,SRB,8657,15563,13329,65421,17376,7864,128210,9303,16535,14165,65563,13779,9573,128918,543654

In [10]:
refugee.columns

Index(['Year', 'Country of Asylum', 'Country of Origin',
       'Country of Asylum ISO', 'Country of Origin ISO', 'Female 0 - 4',
       'Female 5 - 11', 'Female 12 - 17', 'Female 18 - 59', 'Female 60+',
       'Female Other', 'Female Total', 'Male 0 - 4', 'Male 5 - 11',
       'Male 12 - 17', 'Male 18 - 59', 'Male 60+', 'Male Other', 'Male Total',
       'Total'],
      dtype='str')

In [11]:
refugee.describe()

,Year,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
count,4661.000000,4661.000000,4.661000e+03,4.661000e+03,4.661000e+03,4661.000000,4.661000e+03,4.661000e+03,4661.000000,4.661000e+03,4.661000e+03,4.661000e+03,4661.000000,4.661000e+03,4.661000e+03,4.661000e+03
mean,2012.732246,7944.582278,1.166187e+04,8.662124e+03,2.972893e+04,3544.249517,2.198520e+04,8.352696e+04,8072.672602,1.201343e+04,9.112376e+03,2.958149e+04,3177.455911,2.140380e+04,8.336123e+04,2.780156e+05
std,6.943670,47612.449305,6.817692e+04,4.977553e+04,1.714929e+05,28063.598895,1.841374e+05,4.128308e+05,48377.248303,7.049394e+04,5.160432e+04,1.652293e+05,23373.433865,1.740902e+05,4.032877e+05,1.319654e+06
min,2001.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,5.000000e+00
25%,2007.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,7.000000e+00,0.000000,0.000000e+00,0.000000e+00,5.000000e+00,0.000000,0.000000e+00,9.000000e+00,1.760000e+02
50%,2013.000000,5.000000,8.000000e+00,8.000000e+00,4.800000e+01,0.000000,1.600000e+01,1.580000e+02,5.000000,8.000000e+00,8.000000e+00,7.700000e+01,0.000000,2.100000e+01,2.080000e+02,2.112000e+03
75%,2019.000000,144.000000,2.320000e+02,1.880000e+02,1.262000e+03,82.000000,3.440000e+02,4.067000e+03,143.000000,2.440000e+02,2.200000e+02,1.951000e+03,97.000000,6.050000e+02,5.643000e+03,3.446300e+04
max,2024.000000,878613.000000,1.660594e+06,1.096779e+06,3.182316e+06,837457.000000,4.323970e+06,7.220071e+06,895400.000000,1.682751e+06,1.116633e+06,2.704253e+06,680577.000000,4.087720e+06,7.092986e+06,3.000298e+07

In [12]:
print("Total raws:", refugee.shape[0])

Total raws: 4661

In [13]:
refugee.duplicated().sum()

np.int64(0)

In [14]:
refugee.isna().sum().sum()

np.int64(0)

In [15]:
refugee_2004 = refugee[refugee['Year'] == 2004]
refugee_2024 = refugee[refugee['Year'] == 2024]

In [16]:
refugee_2004.head()

,Year,Country of Asylum,Country of Origin,Country of Asylum ISO,Country of Origin ISO,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
562,2004,-,Afghanistan,-,AFG,110737,157553,236182,401876,32141,456,938945,111036,160531,248601,436368,37697,571,994804,2691054
563,2004,-,Iran (Islamic Rep. of),-,IRN,210,586,480,2335,103,351,4065,250,694,576,3616,131,490,5757,124690
564,2004,-,Iraq,-,IRQ,4053,7595,15596,30732,2435,1081,61492,4318,8352,16870,50035,2486,1319,83380,358647
565,2004,-,North Macedonia,-,MKD,64,85,67,253,25,20,514,60,91,90,188,39,39,507,5801
566,2004,-,Serbia and Kosovo: S/RES/1244 (1999),-,SRB,3580,16264,13946,68318,19415,51970,173493,3962,17342,14867,67869,15570,56250,175860,579815

In [17]:
countries = gpd.read_file(r"C:\Users\Jamal Amro\Geo_Spatial_Env\workshop5 week6\ne_110m_admin_0_countries.shp")

In [18]:
countries.head()

,featurecla,scalerank,LABELRANK,SOVEREIGNT,SOV_A3,ADM0_DIF,LEVEL,TYPE,TLC,ADMIN,...,FCLASS_TR,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,geometry
0,Admin-0 country,1,6,Fiji,FJI,0,2,Sovereign country,1,Fiji,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((180 -16.06713, 180 -16.55522, ..."
1,Admin-0 country,1,3,United Republic of Tanzania,TZA,0,2,Sovereign country,1,United Republic of Tanzania,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((33.90371 -0.95, 34.07262 -1.05982, 3..."
2,Admin-0 country,1,7,Western Sahara,SAH,0,2,Indeterminate,1,Western Sahara,...,Unrecognized,Unrecognized,Unrecognized,NaN,NaN,Unrecognized,NaN,NaN,NaN,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948..."
3,Admin-0 country,1,2,Canada,CAN,0,2,Sovereign country,1,Canada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((-122.84 49, -122.97421 49.0025..."
4,Admin-0 country,1,2,United States of America,US1,1,2,Country,1,United States of America,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((-122.84 49, -120 49, -117.0312..."

In [19]:
countries.columns

Index(['featurecla', 'scalerank', 'LABELRANK', 'SOVEREIGNT', 'SOV_A3',
       'ADM0_DIF', 'LEVEL', 'TYPE', 'TLC', 'ADMIN',
       ...
       'FCLASS_TR', 'FCLASS_ID', 'FCLASS_PL', 'FCLASS_GR', 'FCLASS_IT',
       'FCLASS_NL', 'FCLASS_SE', 'FCLASS_BD', 'FCLASS_UA', 'geometry'],
      dtype='str', length=169)